class ErrorCode:
    UNAUTHORIZED = 1
    INTERNAL_SERVER_ERROR = 2
    NOT_FOUND = 3
    USER_EXISTED = 4
    USER_NOT_EXISTED = 5
    REQURED_FIELD_MISSING = 6


class ResponseCode:
    INTERNAL_SUCCESS = 1
    INTERNAL_ERROR = 0
    SUCCESS = 200
    REQUEST_INVALID = 400
    UNAUTHORIZED = 403
    NOT_FOUND = 404
    INTERNAL_SERVER_ERROR = 500
