version: "3"

services:
    db:
        container_name: "sombot-db"
        image: postgres:12.4-alpine
        restart: always
        expose:
            - "5432"
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
            interval: 10s
            timeout: 5s
            retries: 5
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata/
        volumes:
            - db_data_dev:/var/lib/postgresql/data/pgdata
        env_file:
            - .env

    server-api:
        build: ./
        command: python3 dev.py
        expose:
            - "5000"
        ports:
            - "80:5000"
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - ./:/usr/src/app/
        env_file:
            - .env

volumes:
    db_data_dev:
