version: "3"

services:
    db:
        container_name: "sombot-db"
        image: postgres:12.4-alpine
        restart: always
        expose:
            - "5432"
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
            interval: 10s
            timeout: 5s
            retries: 5
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata/
        volumes:
            - database_volume:/var/lib/postgresql/data/savedata
        env_file:
            - ./.env

    server-api:
        build: ./
        depends_on:
            db:
                condition: service_healthy
        command: waitress-serve --port=3000 --call 'run:app'
        volumes:
            - ./:/usr/src/app/
        env_file:
            - ./.env

    proxy-service:
        image: nginx:1.18.0-alpine
        volumes:
            - ./leaf.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        depends_on:
            - "server-api"

volumes:
    database_volume:
